trigger: none

pool:
  name: 'Maven Local'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'
    cleanDestinationDirectory: false
- task: CmdLine@2
  displayName: 'Captura groupId, artifactId e version do projeto'
  inputs:
    script: |
      echo "Capturando o groupId, artifactId e versão do projeto"
      GROUP_ID=$(mvn help:evaluate -Dexpression=project.groupId -q -DforceStdout)
      ARTIFACT_ID=$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)
      VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
      echo "groupId capturado: $GROUP_ID"
      echo "artifactId capturado: $ARTIFACT_ID"
      echo "Versão capturada: $VERSION"
      echo "##vso[task.setvariable variable=GROUP_ID]$GROUP_ID"
      echo "##vso[task.setvariable variable=ARTIFACT_ID]$ARTIFACT_ID"
      echo "##vso[task.setvariable variable=VERSION]$VERSION"
- task: Maven@3
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean verify'
- task: CmdLine@2
  displayName: Sonar Quality Gate
  inputs:
    script: |
      echo "###### INFO: Rodando Sonar Scanner na Branch = $(Build.SourceBranchName) ###### "
      sonar-scanner -Dsonar.projectKey=$(ARTIFACT_ID) -Dsonar.sources=src/main/java/ -Dsonar.java.binaries=target/classes -Dsonar.qualitygate.wait=true